GET http://localhost:5000/api/v1/user/

###
POST http://localhost:5000/api/v1/auth/register
Content-Type: application/json

{
    "email": "admin2@gmail.com",
    "password": "123456"
}

###
POST http://localhost:5000/api/v1/auth/login
Content-Type: application/json

{
    "email": "admin2@gmail.com",
    "password": "123456"
}

###
GET http://localhost:5000/api/v1/user/
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpZCI6MywiZW1haWwiOiJhZG1pbjJAZ21haWwuY29tIiwicm9sZV9jb2RlIjoiUjMiLCJpYXQiOjE3MjY1MzgwMzcsImV4cCI6MTcyNjk3MDAzN30.azRiVjtgdaF_SR8By01e7n8T320LpQ0Ghhwk9_hyu08